allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@supabase/auth-js@2.110.6"
  - "@supabase/functions-js@2.110.6"
  - "@supabase/postgrest-js@2.110.6"
  - "@supabase/realtime-js@2.110.6"
  - "@supabase/storage-js@2.110.6"
  - "@supabase/supabase-js@2.110.6"
  - prettier-plugin-tailwindcss@0.8.1
